### ISSUE TITLE
Bar not refreshing

### ISSUE THREAD

**Issue by drewman** [Jean-Tinland/simple-bar#10]
Love the bar! Just installed it and I can't get it to refresh. The bar stays in the state when it was initially loaded.

When I click on a workspace I see the following console error:
<img width="946" alt="Screen Shot 2020-09-11 at 11 50 35 AM" src="https://user-images.githubusercontent.com/1541761/92962092-45309300-f425-11ea-970e-bcafc1e2c72e.png">

Not sure if this is a user error or what I can do to get this working correctly.

**Comment by drewman** [comment]
Changing my yabai signal from `tell application \"Übersicht\"` to `'tell application id \"tracesOf.Uebersicht\"` got it working. Maybe the readme should be updated?

**Comment by Jean-Tinland** [comment]
Hi, thank you for reporting this, I updatet the README file with this alternative syntax for yabai signals.
Since this syntax is not working for me (and I don't know why, yet), you will find the two of them in the README.

I took the opportunity to add some missing signals I was using but which were not display in the README file.
