### ISSUE TITLE
something went wrong with data.jsx

### ISSUE THREAD

**Issue by mohabariza** [Jean-Tinland/simple-bar#109]
Running Yabai on the latest update of MacOs, used github to download simple-bar, but this is what i see. 
<img width="1680" alt="Screen Shot 2021-03-06 at 3 04 56 PM" src="https://user-images.githubusercontent.com/69372648/110219485-81512780-7e8d-11eb-9f48-70d7d25280e6.png">

**Comment by Jean-Tinland** [comment]
Hi!

The right part of simple-bar is displaying some data coming from multiple commands. If you are seeing this error it's because one of these commands in failing.

In order to detect which widget is causing that error, you can toggle them one by one until you find the culprit.
![image](https://user-images.githubusercontent.com/43068795/110338073-e2f8c980-8026-11eb-8cd9-8992625ca591.png)

You can open the settings module by clicking on simple-bar then press `cmd + ,` at the same time.

Let me know if this helps you. Tell me which widget is causing you trouble and I'll look into it.

**Comment by mohabariza** [comment]
Thanks so much for the reply, but the problem seems to have fixed itself when i reinstalled simple-bar to try this fix. 👍  
<img width="1439" alt="Screen Shot 2021-03-08 at 1 22 38 PM" src="https://user-images.githubusercontent.com/69372648/110364143-6c050600-8011-11eb-9303-48ea9eebf3fc.png">
