### ISSUE TITLE
[Feature Request] VPN Support for Wireguard and Zerotier

### ISSUE THREAD

**Issue by issmirnov** [Jean-Tinland/simple-bar#119]
First of all, thank you for a lovely project! I had my own powerline widgets, but with Big Sur a lot broke. Your style is much better.

Would it be possible to extend the VPN widget to support [wireguard](https://www.wireguard.com/) and [zerotier](https://www.zerotier.com/)? Both are becoming more popular these days.

Alternatively, some pointers would be welcome. Perhaps I may find time to contribute those widgets if you have a few tips.

Thanks in advance!

**Comment by Jean-Tinland** [comment]
Thank you, I'm glad you are liking it!

I can look into it and maybe update the current VPN widget in order to implement compatibility with other VPN softwares. 
It just need to be optimally worked & unified so we don't need to create a widget for each VPS software. Also it can only work if these softwares are exposing a way of getting information and trigger actions like `Viscosity` does with Applescript.

As for the inputs about widgets creation you can look into the data.jsx file how each individual widget is loaded.
Each of these widgets is fed with the result of a command that takes in its parameters the list of all active widgets (extracted from settings) among other parameters.
Theses widgets are styled with CSS declared in 2 files (dark & light theme) and imported in data.jsx.

I don't know if you already knew what i explained above so feel free to ask me more precisely about that.

**Comment by Jean-Tinland** [comment]
If anything is possible with command line you should be able to do it in the new "User widget" module in settings. I'm closing this for now, feel free to re open it if necessary!

See #176 for more information.
