### ISSUE TITLE
overlap still remain when bsp or stack enabled

### ISSUE THREAD

**Issue by rmGFW** [Jean-Tinland/simple-bar#130]
![image](https://user-images.githubusercontent.com/66858140/118394297-6c0b2d00-b676-11eb-80e1-96b46dd6f97e.png)
this is the screenshot of my workspace ,the red mark is the simple-bar, but it was coverd by alacritty window .

another problem . 
i have made the SIP disabled , and also run cmd `yabai --load-sa` 。but simple-bar still can't create new workspace

**Comment by rmGFW** [comment]
by the way 

how can i hide the macos builtin bar in the top

**Comment by Jean-Tinland** [comment]
Hi!

In order to make space for simple-bar, you'll need to configure some things in your `.yabairc`.
For example:

```sh
yabai -m config layout                       stack # bsp
yabai -m config top_padding                  20
yabai -m config bottom_padding               20
yabai -m config left_padding                 20
yabai -m config right_padding                20
yabai -m config window_gap                   10
yabai -m config external_bar                 all:28:0
```

As you can see you can precisely set the spacing of all your windows and you external bar height.

About hiding the built in top bar, you'll need to open your `System preferences > Dock & Menu Bar`. You'll find in this screen a setting (see screenshot below).
<img width="706" alt="Screenshot 2021-05-16 at 21 10 43" src="https://user-images.githubusercontent.com/43068795/118409584-5a805000-b68b-11eb-9d1d-36e1dded950d.png">

And for the last question about space creation, have you followed every steps indicated [here](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup)?
Everything should be working correctly if you do exactly as explained in this link.

Let me know if you have any problem while solving this.

**Comment by rmGFW** [comment]
thanks ! it works

**Comment by rmGFW** [comment]
> Hi!
> 
> In order to make space for simple-bar, you'll need to configure some things in your `.yabairc`.
> For example:
> 
> ```shell
> yabai -m config layout                       stack # bsp
> yabai -m config top_padding                  20
> yabai -m config bottom_padding               20
> yabai -m config left_padding                 20
> yabai -m config right_padding                20
> yabai -m config window_gap                   10
> yabai -m config external_bar                 all:28:0
> ```
> 
> As you can see you can precisely set the spacing of all your windows and you external bar height.
> 
> About hiding the built in top bar, you'll need to open your `System preferences > Dock & Menu Bar`. You'll find in this screen a setting (see screenshot below).
> <img alt="Screenshot 2021-05-16 at 21 10 43" width="706" src="https://user-images.githubusercontent.com/43068795/118409584-5a805000-b68b-11eb-9d1d-36e1dded950d.png">
> 
> And for the last question about space creation, have you followed every steps indicated [here](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup)?
> Everything should be working correctly if you do exactly as explained in this link.
> 
> Let me know if you have any problem while solving this.

thanks!
