### ISSUE TITLE
Couple of Questions

### ISSUE THREAD

**Issue by MikoMagni** [Jean-Tinland/simple-bar#149]
Hi @Jean-Tinland,

I noticed that the Spotify Song Tile is no longer scrolling on hover. 

Did you remove the functionality? Or am I having a senior moment? 

<img width="292" alt="image" src="https://user-images.githubusercontent.com/2527231/122311681-e7038400-cf51-11eb-850a-5b9aa7d24bad.png">

Also, I'm having an odd issue with the weather widget.

I live in Adelaide, South Australia https://wttr.in/Adelaide

"Adelaide" in Simple Bar settings **used to work perfectly**. However, in the past few commits, the location is no longer working. 

<img width="325" alt="image" src="https://user-images.githubusercontent.com/2527231/122312359-30a09e80-cf53-11eb-9593-7918727287f4.png">

<img width="418" alt="image" src="https://user-images.githubusercontent.com/2527231/122312266-0353f080-cf53-11eb-92a7-025025b22644.png">

When I click on the Weather widget, it opens https://wttr.in/Tarndanya?m resulting in a 404. 

I triple-checked system preferences to make sure that Übersicht has access to my location. 

<img width="588" alt="image" src="https://user-images.githubusercontent.com/2527231/122312136-c12aaf00-cf52-11eb-8412-455c32a514ef.png">

Would you happen to know what could be causing it?

Cheers,
Miko

**Comment by Jean-Tinland** [comment]
Hi!

There was indeed a bug in the weather widget when location was manually set. I just fixed it, let mo know if this solves your issue. :)

And for the Spotify widget scroll on hover, it only happens if the "title - artist" is wider than a determined amount of pixel. I unified all the widgets having this behaviour in order to let the user set the scroll speed in settings (`Sliding animation pace` in `global` tab).

https://user-images.githubusercontent.com/43068795/122345841-98052100-cf48-11eb-8d19-86f03c029e8f.mov

**Comment by MikoMagni** [comment]
Hi Jean, 

I fixed the Spotify Widget not scrolling by changing the animation speed value and resaving the settings. For some odd reason, it was completely stuck and not moving. All good now!

Also, your latest commit fixed the location! 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/2527231/122350648-8cd3e480-cf8c-11eb-8949-53c60145b523.png">

Thank you :)
