### ISSUE TITLE
Weather widget does not display location properly

### ISSUE THREAD

**Issue by oliver-ni** [Jean-Tinland/simple-bar#155]
Hi! Love your work. Thanks so much for this.

I ran into one issue with the Weather widget not displaying properly:

<img width="313" alt="Screen Shot 2021-06-26 at 2 08 17 AM" src="https://user-images.githubusercontent.com/20295134/123508312-716b7800-d623-11eb-87ea-e8f7f5ceccb8.png">

Am I doing something wrong here?

**Comment by Jean-Tinland** [comment]
Oops, that was my mistake, this is fixed now!

Be careful there also has been some changes made regarding the signals that needed to be set in your `.yabairc`: they are no longer required as simple-bar is now doing that itself ([see this section in the readme file](https://github.com/Jean-Tinland/simple-bar#refresh-bar-on-app-or-workspace-change)).

Also `process` and `spaces` widgets have been merged so you will need to restart both `yabai` & `Übersicht` in order to make everyting work again!

**Comment by oliver-ni** [comment]
Thank you so much!
