### ISSUE TITLE
Feature + Icon Request

### ISSUE THREAD

**Issue by is0n** [Jean-Tinland/simple-bar#157]
# Requested Feature
Widget that displays what mode of yabai you are currently using.

A command that can be used to accomplish this:

```
$ yabai -m query --spaces --space | jq -re '.type'
```

I would try to do this myself but I don't know any javascript ¯\_(ツ)_/¯

# Requested Icon
Icon for the [Min Browser](https://minbrowser.org/) and [Pine](https://github.com/lukakerr/Pine).

**Comment by Jean-Tinland** [comment]
Hi, it's been a while since I wanted to implement an elegant way of letting the user know in which layout type the current space is.

I already have the information, I just don't know where to display it.

I could add an indicator right here:
![Screenshot 2021-06-30 at 19 23 04](https://user-images.githubusercontent.com/43068795/124004790-a9ced580-d9d8-11eb-9e77-38dc415203ae.jpg)

I'll let you know if I come up with something!

I'm adding both the requested icons soon! :)

**Comment by is0n** [comment]
I think that putting the layout type right next to process name is a great idea and I'm happy to hear that the icons will both be coming soon! 

Since there's not much else to say I'll be closing the issue.

**Comment by Jean-Tinland** [comment]
Hi!

I added those 2 app icons plus a new setting that show the current space layout type:
![image](https://user-images.githubusercontent.com/43068795/126062279-91c3b603-9ba8-46c8-8ba9-e02ccc5aaf18.png)

Let me know if this is OK. :)

**Comment by is0n** [comment]
The widget works as expected and isn't distracting nor hidden. I think that it could look better if there was something surrounding the widget*, as opposed to just having plain text, but other than, that it looks great!

*similar to the widgets at the right of the bar that consist of plain text with something surrounding them.

**Comment by Jean-Tinland** [comment]
I see, it is indeed a bit simple, I'll think of a way of improving its look without making look like it could be an interactive element!

I'm glad it is suits you as is for now :)
