### ISSUE TITLE
Any future plan?

### ISSUE THREAD

**Issue by yanzhang0219** [Jean-Tinland/simple-bar#176]
Hello Jean,

This menu bar widget is really fantastic ❤️. It has been my must-have daily usage.

I am wondering whether you have any future plans to add more widgets such as a widget for CPU/Mem/Disk usage? Or are you considering developing a plugin system or something like that (like provide some API) so that we can easily add what we need onto the menu bar?

A good idea is like [SwiftBar](https://github.com/swiftbar/SwiftBar) or [xbar](https://github.com/matryer/xbar). Imagine this: we write a shell script to run something we need and we can add the result of this script onto simple-bar as a widget. Wow, it will be really nice!

Thank you very much.

**Comment by Jean-Tinland** [comment]
Hi!

Thank you for your kind words! I'm really pleased I'm not the only one that enjoys using this little project and finds it useful.

I currently haven't enough time to do every thing I wan't regarding simple-bar so I'm simply trying to fix all reported bugs & optimise some things from time to time. I'd like to dive again soon into, first, fixing the latest display bug (since I implemented  the theming system) then implementing new features.

I really like your idea of extensible data display outputting commands or custom scripts!

I'm seeing a new entry in settings letting the user add `n` custom widgets that individually render a new data-widget in which the command/script output is displayed. Each of these custom widget would need to be freely ordered and associated to an icon (optional among all the icons declared in the `icons` file), a refresh frequency and a background color.

Thank you for your message.

**Comment by yanzhang0219** [comment]
Hi Jean,

Thank you for your effort to fix bugs to make this project more shining. I really like it too much, especially its high quality and the details it shows. E.g., when a window is zoomed full-screen, its icon will be highlighted. This is really nice. 

Furthermore, I am so excited about the extensible custom widget system you are planning to implement 🤗. I believe that will be a great milestone for this project and every yabai user will be excited. I am looking forward to trying it soon. Thanks.

**Comment by Jean-Tinland** [comment]
Hi!

I have been working on a draft of custom user widgets as you can see in this video:
https://user-images.githubusercontent.com/43068795/129361910-10c8c23a-d67c-451e-8b23-dfb994a96649.mp4

Let me if this is meeting your expectations! I'm planning to make some slight adjustments before publishing it.

**Comment by yanzhang0219** [comment]
Wow, this looks great! I think it would be better if ANSI color can be supported. 
Thanks for your efforts and cannot wait to give it a shot.

**Comment by Jean-Tinland** [comment]
I just merged this branch with the master one! You can try this new system and let me know if this is answering your need!

As requested you can set a custom (valid css) color!

**Comment by Jean-Tinland** [comment]
I'll close this as the feature is now implemented, do not hesitate to open a new issue if you encounter any problem.
