### ISSUE TITLE
Auto hide widget children 

### ISSUE THREAD

**Issue by bhedavivek** [Jean-Tinland/simple-bar#233]
### Problem
Widgets overlap on laptop's display when there are too many widgets open/active

![image](https://user-images.githubusercontent.com/12003668/138167153-92b8bee9-d593-49b1-a2b4-96a2d6be1519.png)

#### Possible solutions
- Only display icons when too many widgets in bar
- Auto expand widgets to display children on hover?

**Comment by Jean-Tinland** [comment]
I don't think I can fix this issue on my end.

That said, with the latest settings additions, actions can be taken in order to reduce the size taken by the process widget and data widget can be moved to specific screen in order to prevent clutter on your main screen.

If you don't work on external monitor I'm afraid the only solution is to choose wisely what you want to see.
