### ISSUE TITLE
Crypto Precision

### ISSUE THREAD

**Issue by AurevoirXavier** [Jean-Tinland/simple-bar#250]
I set to 3:

![image](https://user-images.githubusercontent.com/16152305/141773020-834d5ad9-9973-4fc4-ad65-9c065e2a8518.png)

And it should be 47.000 and 0.088.

**Comment by Jean-Tinland** [comment]
This precision system is working as explained in [this documentation](https://devdocs.io/javascript/global_objects/number/toprecision).

A precision of 3 will make the widget display only 3 digit (before and after the decimals). This precision system is not the equivalent of a rounding system.

If it seems more logical to work with a rounding system I can easily switch to it instead of this precision system.

Let me know what you think. :)

**Comment by AurevoirXavier** [comment]
IMHO, rounding system is better.

**Comment by Jean-Tinland** [comment]
Precision system has been replaced by a decimal rounding system. :)
