### ISSUE TITLE
Show data only on main screen

### ISSUE THREAD

**Issue by kvndrsslr** [Jean-Tinland/simple-bar#309]
Hey @Jean-Tinland, I loved to be able to show the data widgets only on main screen and have space and window information on all screens.
It seems like this functionality was removed.
I'll go back to the last commit that had that but want to ask if you plan on a way to reintroduce that.
If you point me in the right direction I can make a PR too.

**Comment by Jean-Tinland** [comment]
Hi! I didn't think of that when I merged the two widgets! I will reintroduce this options in the settings module soon :)

**Comment by Jean-Tinland** [comment]
A bit later than I was hoping, I added the option to hide or show every widget on `simple-bar` on specific display(s) (spaces, process, data widgets, custom user widgets... everything!)

I updated the documentation according to these changes.

In every tab settings, you'll find a new entry "Show on display n°". In this field, you can add a list of monitor indexes like `1,2` for displaying a particular widget on your first and second displays or `3` in order to display it only on this monitor. Leave it blank to display the widget on every display(s).
