### ISSUE TITLE
Option to disable shadow

### ISSUE THREAD

**Issue by deusipse** [Jean-Tinland/simple-bar#379]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be an option to turn off the shadow, and I have yabai running with shadows off. 
(in yabairc) `yabai -m config window_shadow  off`
<img width="395" alt="image" src="https://github.com/Jean-Tinland/simple-bar/assets/69350438/f1b0f9c3-2177-49b8-8122-11845c737d45"> The shadow can still be seen, and shadows are not present for any other applications.
Current available options: 
<img width="692" alt="image" src="https://github.com/Jean-Tinland/simple-bar/assets/69350438/eaf8c7c9-129d-40d1-b009-0cb128d955a4">

**Describe the solution you'd like**
An option to turn off the shadow.

While I'm at it, thanks for making this bar, it is by far the best one I've used for two years now!

**Comment by Jean-Tinland** [comment]
Hmm that's weird, I just tested disabling and enabling shadow and `simple-bar` is normally checking on each refresh if yabai has enabled shadow or not by running this command `yabai -m config window_shadow`. Depending on the output, It removes automatically its shadow.

Can you try to run this command and see if it returns `off`?

Otherwise, if you want an easy fix, you can simply add these lines in your custom styles tab (in settings):

```css
.simple-bar {
  box-shadow: none !important;
}
```

**Comment by deusipse** [comment]
<img width="543" alt="image" src="https://github.com/Jean-Tinland/simple-bar/assets/69350438/445ba270-5bb0-4a2a-8089-48cfcbe3cd18">

Interesting, it says `off` when I ran the command...
Also weirdly enough, the css doesn't make the shadow go away:
<img width="1099" alt="image" src="https://github.com/Jean-Tinland/simple-bar/assets/69350438/f9c291a1-369d-4549-bb13-f2cff69ee297">
The shadow is still there. It seems that the `box-shadow: none !important;` only made the red outline not appear when selecting the bar.

And now I tried updating it to the latest git commit 6abd85084b30fa14673ca189036e6cb8bc1fdf42: the bar doesn't load at all and has this error:
<img width="666" alt="image" src="https://github.com/Jean-Tinland/simple-bar/assets/69350438/d47727da-f1f5-4964-a002-9ceae4279654">

My previous install worked and was commit number 3d38feca9418597ba416f6d6f3a0160f2a1182b9. Not sure what's going on, I've never had any issues like this before! I'm using the latest Ubersicht 1.6.82 on Sonama 14.1.

**Comment by Jean-Tinland** [comment]
Oh, I think I know what is happening. It seems that the shadow you see are not `.simple-bar` shadows because they are rightly removed. 
I simply didn't removed all the children shadows and they are projected below the bar.

I just pushed a fix that should make all shadow disappear :)

I also tried to fix the error you saw, please let me know if every thing is working fine again.

**Comment by deusipse** [comment]
Yep - this fixed everything!! Thank you so much for your work and quick response :D
