### ISSUE TITLE
Won't switch spaces.

### ISSUE THREAD

**Issue by shps18ppt** [Jean-Tinland/simple-bar#387]
https://github.com/Jean-Tinland/simple-bar/assets/131682899/c197d2e1-cd98-4dfe-9db1-7b4cc6d532fe

Is there anything I can do? I don't know how to reproduce this issue.

**Comment by shps18ppt** [comment]
@Jean-Tinland

**Comment by Jean-Tinland** [comment]
Sorry for my late response!
I think you are not the only one experiencing this issue.

In order to help me while trying to resolve this, can you please tell me what is the version of the following:
- yabai
- übersicht
- mac os

Also, can you try to open the Übersicht console and look for any error when you click on the spaces in simple-bar? You can see on the image below where to find this menu.

<img width="264" alt="image" src="https://github.com/Jean-Tinland/simple-bar/assets/43068795/bced57c5-4bea-4735-9bc9-9322d989706c">

Please copy and paste here the error if there is one.

Otherwise, can you try to manually switch space by executing this command in your terminal?

```shell
# where "2" is the number of the space you want to focus
yabai -m space --focus 2
```

Let me know if there is an error while executing this command as this is what is used by simple-bar in order to change space.

**Comment by shps18ppt** [comment]
Looks like there's an error. 

```
Unhandled Promise Rejection: Error: cannot focus space due to an error with the scripting-addition.
```

Anyways, here are the information you needed:
```
macos: sonoma 14.0
uebersicht: 1.6
yabai: 6.0
```

Thanks for your reply.

**Comment by Carbone13** [comment]
You need to disable SIP and enable the scripting addition, see [disabling SIP](https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection) and [enabling the scripting addition](https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition).
