### ISSUE TITLE
Multiple Window Icons

### ISSUE THREAD

**Issue by vod3** [Jean-Tinland/simple-bar#51]
Using the PiP Feature in Firefox causes the Firefoxicons in the Spaceswitcher to appear multiple times.
![grafik](https://user-images.githubusercontent.com/22642893/98233423-50082f80-1f5f-11eb-859e-8645e7fcf663.png)

Sometimes it happens too when using the preview feature in macos, here in workspace 5, but the preview is opened in 6:
![grafik](https://user-images.githubusercontent.com/22642893/98233522-77f79300-1f5f-11eb-8894-a884a50e5e0b.png)

Any ideas?
Thx!

**Comment by Jean-Tinland** [comment]
You could use this command in your terminal while you are on the said space:

```sh
yabai -m query --windows --space
```

In order to get current space windows list and identify theses windows title.

Then you can had these titles here:

<img width="678" alt="image" src="https://user-images.githubusercontent.com/43068795/98235975-e25e0280-1f62-11eb-9de4-efe96b47cc6a.png">

Doing so they will be ignored by simple-bar.

Let me know if this solves your problem.

**Comment by Jean-Tinland** [comment]
This should solve this issue. Feel free to reopen if if not :)
