### ISSUE TITLE
Bug on adding second display in Big Sur

### ISSUE THREAD

**Issue by anujc4** [Jean-Tinland/simple-bar#55]
I started using simple-bar with a secondary display attached. For some reason, my simple-bar looks like this
![image](https://user-images.githubusercontent.com/9458914/99748547-a97e6b80-2ad4-11eb-8951-6fb159642629.png)

I think this might be a CSS issue and it is only happening on the second display. While I try to figure it out, I'm posting this issue to see if anyone else is facing this issue.

**Comment by MikoMagni** [comment]
@anujc4 make sure to set simple-bar spaces-jsx to only display on your primary monitor and simple-bar spaces-2-jsx to only show on your secondary monitor. 

<img width="433" alt="image" src="https://user-images.githubusercontent.com/2527231/99919509-cd101300-2d6d-11eb-8f89-02a08e83a95d.png">

**Comment by Jean-Tinland** [comment]
It indeed seems that you have both the spaces and spaces-2 actived on your displays.

Enabling only one on the right display will solve this problem.

Otherwise, I juste pushed an update including a revamp (created by @theshortcut) of multiple display handling which automatically resolve this issue by removing the spaces-2 widget and by handling everything in the spaces widget.

So you'll just have to pull in order to fix that.

**Comment by anujc4** [comment]
The fix worked! Thanks, Jean 👍
