### ISSUE TITLE
Delay using the applescript method to refresh yabai spaces

### ISSUE THREAD

**Issue by Rougemoot** [Jean-Tinland/simple-bar#56]
Hi!

I love simple-bar, its modularity, its themes... it's just great.

The one thing that's driving me crazy, though, is that when I change spaces (with yabai), it takes about a second to refresh. Of course I did add the signals stuff in the yabai config, and even set the refresh rate in the widget to `false` to make sure it was indeed the applescript stuff that refreshed the widget but no, I guess applescript is just that slow.

I'm not sure this is something you can do much about but this is the only place I could reach out to ask:

Isn't there a better way?

I've been trying spacebar, which is a direct fork of yabai and its rudimentary status bar stuff. There the space indicator change is of course instant, but spacebar is nowhere as nice as what one can achieve with Ubersicht.

I hope we can find another way to refresh simple-bar (or any Ubersicht widget, I guess).

**Comment by Jean-Tinland** [comment]
Hi @Rougemoot,

Thanks for using simple-bar! :)

I'm afraid there is little we can to in order to improve things.

You could always try to set `dash` shell as executing shell in `simple-bar` settings:
<img width="674" alt="image" src="https://user-images.githubusercontent.com/43068795/100077578-cf906c80-2e42-11eb-9fff-bfe6fb0dcd43.png">

Also you can run `brew edit yabai` and add these lines under Environment in the daemon plist declaration:

```xml
<key>SHELL</key>
<string>/bin/dash</string>
```

After that you'll need to `brew reinstall yabai` and `brew services restart koekeishiya/formulae/yabai`.

These should speed up a bit the `yabai` & `simple-bar` parts.

Let me know if you see some changes for the better.

**Comment by wilsongoode** [comment]
Thanks for the tips here! I'll share my story here in case someone else has the same problems later.

I noticed that rerunning `.yabairc` when I was adding the signals led to about 50 signals being active at once. This obviously became quite slow and I was struggling to figure out why so much of my CPU was being hit. I first switched simple-bar to using `dash`, then ran `yabai -m signal --list` and discovered all of the duplicates. If anyone else has this issue, simply running `brew services restart yabai` fixed this for me. Then I `brew edit`ed `yabai` and found `dash` to be much snappier overall.
