### ISSUE TITLE
[Icons] Depending on the language: Icons not shown if title is translated

### ISSUE THREAD

**Issue by christo-ph** [Jean-Tinland/simple-bar#65]
Hi, when checking https://github.com/Jean-Tinland/simple-bar/pull/11 I noticed that the `message` icon was already added.

My language is set to German in macOS. So the window title is 'Nachrichten'. The mapping here does not work. Is there a workaround?

Thanks.

**Comment by Jean-Tinland** [comment]
I must say I didn't anticipate this issue. I really don't know if I want to implement a multilingual system into simple-bar. It could become rapidly heavy in order to support more and more languages.

The easiest fix for now is to add an entry in `data.js`:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/43068795/101179436-7eeeef80-364a-11eb-852e-9e67238f3ec5.png">
It should work.

Are you okay with that?

**Comment by christo-ph** [comment]
I am okay with that. Shall I create PRs to have that on master?

**Comment by Jean-Tinland** [comment]
I added it on master at the end of the `data.js` file. You'll find a comment `// German app names` at the end of this file.

If you encounter some other app that you need to add, feel free to add them locally and then create a PR that group several icons at once.
