### ISSUE TITLE
After restarting my computer (Big Sur) my Dock.app didn't work and after uninstalling yabai, my dock was dead, had to reinstall macOS >:(

### ISSUE THREAD

**Issue by wantyapps** [Jean-Tinland/simple-bar#95]

**Comment by Jean-Tinland** [comment]
I'm sorry to hear that but I can't really say what happened here, maybe you could open an issue in the [yabai issue section](https://github.com/koekeishiya/yabai/issues/).

Since simple-bar is calling yabai commands but nothing more related to the dock.app, It's pretty impossible that it directly caused this issue.

**Comment by Jean-Tinland** [comment]
As it seems to not be related to simple-bar I'll close this for now but feel free to post here or re open it if necessary.
